apiVersion: v1
kind: ConfigMap
metadata:
{{- include "common.metadata"  . | nindent 2 }}
{{- if .Values.configMapAnnotations }}
  {{- toYaml .Values.configMapAnnotations | nindent 4 }}
{{- end }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}