apiVersion: apps/v1
kind: DaemonSet
metadata:
{{- include "common.metadata" . | nindent 2 }}
{{- if .Values.daemonsetAnnotations }}
  {{- toYaml .Values.daemonsetAnnotations | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
    {{- if .Values.podLabels }}
      {{- toYaml .Values.podLabels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
      {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "object.name" . }}
          image: {{ .Values.image.repository | default "teymurgahramanov/from-node-exporter" }}:{{ .Values.image.tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: metrics
              containerPort: {{ .Values.config.exporter.metricsListenPort | default 8080 }}
          volumeMounts:
            - name: configmap
              mountPath: /config.yaml
              subPath: config.yaml
          {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: configmap
          configMap:
            name: {{ include "object.name" . }}
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}