apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeping.fullname" . }}
  labels:
    {{- include "kubeping.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeping.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeping.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeping.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}