apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeping.fullname" . }}
  labels:
    {{- include "kubeping.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeping.fullname" . }}
  labels:
    {{- include "kubeping.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeping.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kubeping.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
