apiVersion: v1
kind: Service
metadata:
{{- include "common.metadata" . | nindent 2 }}
{{- if .Values.serviceAnnotations }}
  {{- toYaml .Values.serviceAnnotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.config.exporter.metricsListenPort | default 8080 }}
      targetPort: {{ .Values.config.exporter.metricsListenPort | default 8080 }}
      protocol: TCP
  selector:
    {{- include "common.labels" . | nindent 4 }}
  {{- if .Values.podLabels }}
    {{- toYaml .Values.podLabels | nindent 4 }}
  {{- end }}